---
title: "kegg-graph"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{kegg-graph}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r load-fake-results}
human_genes <- c("hsa:5594", "hsa:5894", "hsa:5604", "hsa:2002")
compounds_1 <- c("C00002", "C00008", "C00076")
compounds_2 <- c("C00022")
compounds_3 <- c("C00076")

res_genes <- data.frame(
  KEGGID = human_genes,
  log2FoldChange = rnorm(length(human_genes), mean = 0, sd = 1)
)
res_metabo_1 <- data.frame(
  KEGG = compounds_1,
  log2FC = rnorm(length(compounds_1), mean = 0, sd = 1)
)
res_metabo_2 <- data.frame(
  KEGG_ids = compounds_2,
  log2FoldChange = rnorm(length(compounds_2), mean = 0, sd = 1)
)
res_metabo_3 <- data.frame(
  KEGG_ids = compounds_3,
  log2FoldChange = rnorm(length(compounds_3), mean = 0, sd = 1)
)

de_results_list <- list(
  trans = list(
    de_table = res_genes,
    value_column = "log2FoldChange",
    feature_column = "KEGGID"
  ),
  metabo_1 = list(
    de_table = res_metabo_1,
    value_column = "log2 FC",
    feature_column = "KEGG"
  ),
  metabo_2 = list(
    de_table = res_metabo_2,
    value_column = "log2FoldChange",
    feature_column = "KEGG_ids"
  )
)

de_results_list_with_repetition <- list(
  genes = list(
    de_table = res_genes,
    value_column = "log2FoldChange",
    feature_column = "KEGGID"
  ),
  metabo_1 = list(
    de_table = res_metabo_1,
    value_column = "log2FC",
    feature_column = "KEGG"
  ),
  metabo_2 = list(
    de_table = res_metabo_2,
    value_column = "log2FoldChange",
    feature_column = "KEGG_ids"
  ),
  metabo_3 = list(
    de_table = res_metabo_3,
    value_column = "log2FoldChange",
    feature_column = "KEGG_ids"
  )
)

```

```{r load-fake-DE, eval = F}
  # Human MAPK signaling pathway genes
res_genes$KEGG <- gene_based_interface(human_genes, from = "SYMBOL", to = "KEGG", organism = "human")
res_metabo$KEGG_ids <- res_metabo$rownames
res_trans$KEGGID <- res_trans$rownames
# annotation_dbi_interface("SYMBOL", "ENTREZID", human_genes, organism = "human")
# prot <- annotation_dbi_interface("SYMBOL", "UNIPROT", human_genes, organism = "human")
# annotation_dbi_interface("UNIPROT", "ENTREZID", prot, organism = "human")
```





```{r use-package}
devtools::load_all()
graph <- ggkegg_to_igraph("hsa04010", organism = "hsa", de_results = de_results_list, return_type = "visNetwork")
 graph
```

```{r, eval = F}
library(pathview)
data(gse16873.d)
pv_out <- pathview(gene.data = gse16873.d[, 1], pathway.id = "04110", species = "hsa")
```

